spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: psw1234
    driver-class-name : org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
